import type { Activity, Area, Building, InfrastructurePoint, SurveyRecord } from "./types";

const evidence = (labels: string[]) =>
  labels.map((label, index) => ({ id: `EV-${index + 1}`, label, added: index < labels.length - 1 }));

export const areas: Area[] = [
  { id: "ZONE-A", name: "Survey Zone A", plannedPoints: 220, completedPoints: 176, buildings: 92, poles: 54, premises: 1320, status: "Validated" },
  { id: "ZONE-B", name: "Survey Zone B", plannedPoints: 185, completedPoints: 122, buildings: 68, poles: 41, premises: 940, status: "Review Required" },
  { id: "ZONE-C", name: "Survey Zone C", plannedPoints: 240, completedPoints: 139, buildings: 74, poles: 48, premises: 1015, status: "Review Required" },
  { id: "ZONE-D", name: "Survey Zone D", plannedPoints: 160, completedPoints: 88, buildings: 43, poles: 31, premises: 620, status: "Incomplete" }
];

export const technicians = ["Nadia Salem", "Kareem Naser", "Yousef Amin", "Maya Faris", "Omar Jad"];

export const buildings: Building[] = [
  {
    id: "BLD-A-001",
    surveyId: "SUR-A-0001",
    date: "2026-08-26",
    technician: "Nadia Salem",
    team: "Survey Team North",
    city: "Harborview",
    areaId: "ZONE-A",
    latitude: "32.018410",
    longitude: "35.872210",
    gpsAccuracy: 4,
    streetRef: "Block A / Street 12",
    type: "Apartment Block",
    status: "Occupied",
    floors: 6,
    entrances: 2,
    units: 36,
    occupiedUnits: 31,
    estimatedPremises: 38,
    commercialUnits: 2,
    existingTelecom: "Copper riser present",
    accessType: "Main entrance access approved",
    facadeType: "Internal riser preferred",
    dropCableAccess: "Facade and stairwell route available",
    closestNetworkPoint: "POL-A-001",
    distanceToNetwork: 38,
    difficulty: "Medium",
    powerAvailability: "Common area power available",
    validationStatus: "Validated",
    validationIssues: [],
    evidence: evidence(["Building Front", "Entrance", "Riser", "Street Reference"]),
    notes: "Suitable for multi-drop FTTH planning with internal riser path."
  },
  {
    id: "BLD-A-002",
    surveyId: "SUR-A-0002",
    date: "2026-08-26",
    technician: "Kareem Naser",
    team: "Survey Team North",
    city: "Harborview",
    areaId: "ZONE-A",
    latitude: "32.019120",
    longitude: "35.873040",
    gpsAccuracy: 5,
    streetRef: "Block A / Street 14",
    type: "Villa",
    status: "Occupied",
    floors: 2,
    entrances: 1,
    units: 1,
    occupiedUnits: 1,
    estimatedPremises: 1,
    commercialUnits: 0,
    existingTelecom: "No visible fiber entry",
    accessType: "Outdoor access only",
    facadeType: "External drop cable",
    dropCableAccess: "Nearest pole route clear",
    closestNetworkPoint: "POL-A-002",
    distanceToNetwork: 24,
    difficulty: "Easy",
    powerAvailability: "Not required",
    validationStatus: "Validated",
    validationIssues: [],
    evidence: evidence(["Building Front", "Facade", "Nearest Pole"]),
    notes: "Low difficulty drop route from existing pole."
  },
  {
    id: "BLD-B-014",
    surveyId: "SUR-B-0014",
    date: "2026-08-27",
    technician: "Maya Faris",
    team: "Survey Team Central",
    city: "Lakeside",
    areaId: "ZONE-B",
    latitude: "32.025880",
    longitude: "35.881760",
    gpsAccuracy: 11,
    streetRef: "Market Lane",
    type: "Mixed Use",
    status: "Partially Occupied",
    floors: 4,
    entrances: 3,
    units: 18,
    occupiedUnits: 12,
    estimatedPremises: 24,
    commercialUnits: 6,
    existingTelecom: "Multiple legacy cable entries",
    accessType: "Requires building manager confirmation",
    facadeType: "Facade route requires approval",
    dropCableAccess: "Route crosses commercial frontage",
    closestNetworkPoint: "POL-B-006",
    distanceToNetwork: 72,
    difficulty: "Difficult",
    powerAvailability: "Common area access not confirmed",
    validationStatus: "Review Required",
    validationIssues: ["GPS accuracy above threshold", "Missing entrance evidence"],
    evidence: evidence(["Building Front", "Commercial Front", "Other"]),
    notes: "Needs second visit with access confirmation."
  },
  {
    id: "BLD-C-021",
    surveyId: "SUR-C-0021",
    date: "2026-08-28",
    technician: "Yousef Amin",
    team: "Survey Team West",
    city: "Stonefield",
    areaId: "ZONE-C",
    latitude: "",
    longitude: "",
    gpsAccuracy: 0,
    streetRef: "West Sector / Unnamed road",
    type: "Residential",
    status: "Under Construction",
    floors: 3,
    entrances: 1,
    units: 9,
    occupiedUnits: 0,
    estimatedPremises: 9,
    commercialUnits: 0,
    existingTelecom: "No infrastructure",
    accessType: "Construction site access",
    facadeType: "Pending final facade",
    dropCableAccess: "Not confirmed",
    closestNetworkPoint: "INF-C-003",
    distanceToNetwork: 118,
    difficulty: "Difficult",
    powerAvailability: "Temporary only",
    validationStatus: "Incomplete",
    validationIssues: ["Missing GPS", "Missing photo evidence", "No nearby distribution point confirmed"],
    evidence: evidence(["Building Front", "Obstruction"]),
    notes: "Record kept incomplete until coordinates and final facade are confirmed."
  }
];

export const infrastructure: InfrastructurePoint[] = [
  {
    id: "POL-A-001",
    surveyId: "SUR-A-0101",
    date: "2026-08-26",
    technician: "Nadia Salem",
    team: "Survey Team North",
    city: "Harborview",
    areaId: "ZONE-A",
    latitude: "32.018760",
    longitude: "35.872560",
    gpsAccuracy: 3,
    streetRef: "Block A / Street 12 corner",
    surveyType: "Existing Pole",
    poleType: "Distribution pole",
    poleMaterial: "Concrete",
    existingOrProposed: "Existing",
    condition: "Suitable",
    heightMeters: 8,
    mountingAvailability: "Two mounting positions available",
    existingCables: "Low density telecom cables",
    spaceAvailable: "Available",
    roadSide: "North side",
    accessCondition: "Clear sidewalk access",
    nearbyBuildingCount: 8,
    distributionUse: "END box mounting",
    poleInstallationRequired: false,
    civilWorkRequired: false,
    pointType: "Pole",
    routeType: "Aerial",
    existingDuct: "N/A",
    chamberOrManhole: "N/A",
    roadCrossing: "No",
    obstruction: "None",
    estimatedRouteDistance: 110,
    validationStatus: "Validated",
    validationIssues: [],
    relatedBuildings: ["BLD-A-001", "BLD-A-002"],
    evidence: evidence(["Pole", "Route", "Nearby Buildings"]),
    notes: "Suitable for planned distribution route."
  },
  {
    id: "POL-B-006",
    surveyId: "SUR-B-0106",
    date: "2026-08-27",
    technician: "Maya Faris",
    team: "Survey Team Central",
    city: "Lakeside",
    areaId: "ZONE-B",
    latitude: "32.026140",
    longitude: "35.882020",
    gpsAccuracy: 7,
    streetRef: "Market Lane / service road",
    surveyType: "Existing Pole",
    poleType: "Roadside pole",
    poleMaterial: "Wood",
    existingOrProposed: "Existing",
    condition: "Replacement Recommended",
    heightMeters: 6,
    mountingAvailability: "Limited",
    existingCables: "Congested low voltage and telecom",
    spaceAvailable: "Limited",
    roadSide: "East side",
    accessCondition: "Commercial frontage obstruction",
    nearbyBuildingCount: 14,
    distributionUse: "Route support only",
    poleInstallationRequired: true,
    civilWorkRequired: true,
    pointType: "Pole",
    routeType: "Aerial",
    existingDuct: "N/A",
    chamberOrManhole: "N/A",
    roadCrossing: "Yes",
    obstruction: "Signage and parked vehicles",
    estimatedRouteDistance: 180,
    validationStatus: "Review Required",
    validationIssues: ["Pole condition requires review", "Civil work required", "Missing clear route photo"],
    relatedBuildings: ["BLD-B-014"],
    evidence: evidence(["Pole", "Obstruction", "Road Crossing"]),
    notes: "Needs engineering decision before design freeze."
  },
  {
    id: "POL-D-004",
    surveyId: "SUR-D-0104",
    date: "2026-08-28",
    technician: "Omar Jad",
    team: "Survey Team East",
    city: "Pinecrest",
    areaId: "ZONE-D",
    latitude: "32.033020",
    longitude: "35.891510",
    gpsAccuracy: 4,
    streetRef: "Eastern access road",
    surveyType: "New Pole Location",
    poleType: "Proposed distribution pole",
    poleMaterial: "Concrete",
    existingOrProposed: "Proposed",
    condition: "New Pole Required",
    heightMeters: 8,
    mountingAvailability: "Planned",
    existingCables: "None",
    spaceAvailable: "Available",
    roadSide: "South side",
    accessCondition: "Soft shoulder",
    nearbyBuildingCount: 11,
    distributionUse: "New END box cluster",
    poleInstallationRequired: true,
    civilWorkRequired: true,
    pointType: "Proposed Pole",
    routeType: "Aerial",
    existingDuct: "N/A",
    chamberOrManhole: "N/A",
    roadCrossing: "No",
    obstruction: "None",
    estimatedRouteDistance: 96,
    validationStatus: "Validated",
    validationIssues: [],
    relatedBuildings: [],
    evidence: evidence(["Route", "Proposed Location", "Nearby Buildings"]),
    notes: "Proposed pole location supports underserved lane."
  },
  {
    id: "INF-C-003",
    surveyId: "SUR-C-0203",
    date: "2026-08-28",
    technician: "Yousef Amin",
    team: "Survey Team West",
    city: "Stonefield",
    areaId: "ZONE-C",
    latitude: "32.029430",
    longitude: "35.867140",
    gpsAccuracy: 6,
    streetRef: "West Sector / road crossing",
    surveyType: "Infrastructure Point",
    poleType: "N/A",
    poleMaterial: "N/A",
    existingOrProposed: "Existing",
    condition: "Review Required",
    heightMeters: 0,
    mountingAvailability: "N/A",
    existingCables: "N/A",
    spaceAvailable: "Pending duct test",
    roadSide: "Center crossing",
    accessCondition: "Traffic control required",
    nearbyBuildingCount: 6,
    distributionUse: "Feeder route crossing",
    poleInstallationRequired: false,
    civilWorkRequired: true,
    pointType: "Road crossing",
    routeType: "Underground",
    existingDuct: "Unknown",
    chamberOrManhole: "Chamber lid visible",
    roadCrossing: "Yes",
    obstruction: "Possible blocked duct",
    estimatedRouteDistance: 64,
    validationStatus: "Review Required",
    validationIssues: ["Duct availability not confirmed", "Civil work required"],
    relatedBuildings: ["BLD-C-021"],
    evidence: evidence(["Route", "Obstruction", "Chamber / Manhole"]),
    notes: "Requires duct test before material planning."
  }
];

export const surveyRecords: SurveyRecord[] = [
  ...buildings.map((building) => ({
    id: building.surveyId,
    date: building.date,
    technician: building.technician,
    team: building.team,
    city: building.city,
    areaId: building.areaId,
    surveyType: "Building" as const,
    latitude: building.latitude,
    longitude: building.longitude,
    gpsAccuracy: building.gpsAccuracy,
    streetRef: building.streetRef,
    objectId: building.id,
    usersOrUnits: building.estimatedPremises,
    validationStatus: building.validationStatus,
    validationIssues: building.validationIssues,
    notes: building.notes
  })),
  ...infrastructure.map((point) => ({
    id: point.surveyId,
    date: point.date,
    technician: point.technician,
    team: point.team,
    city: point.city,
    areaId: point.areaId,
    surveyType: point.surveyType,
    latitude: point.latitude,
    longitude: point.longitude,
    gpsAccuracy: point.gpsAccuracy,
    streetRef: point.streetRef,
    objectId: point.id,
    usersOrUnits: point.nearbyBuildingCount,
    validationStatus: point.validationStatus,
    validationIssues: point.validationIssues,
    notes: point.notes
  }))
];

export const activities: Activity[] = [
  { id: "ACT-SUR-091", time: "2026-08-28 16:35", areaId: "ZONE-C", technician: "Yousef Amin", title: "Road crossing marked for review", note: "INF-C-003 requires duct confirmation and civil planning." },
  { id: "ACT-SUR-090", time: "2026-08-28 14:20", areaId: "ZONE-D", technician: "Omar Jad", title: "New pole location validated", note: "POL-D-004 supports eleven nearby premises." },
  { id: "ACT-SUR-089", time: "2026-08-27 11:10", areaId: "ZONE-B", technician: "Maya Faris", title: "Mixed-use building needs review", note: "BLD-B-014 has GPS accuracy and access evidence issues." },
  { id: "ACT-SUR-088", time: "2026-08-26 15:45", areaId: "ZONE-A", technician: "Nadia Salem", title: "Apartment block validated", note: "BLD-A-001 captured with entrances, units and nearby pole relationship." }
];
